"""
Feedback Diff — semantic comparison between feedback loop iterations.

When COLLECT_ITERATE re-enters AUDIT, the CEO needs to see what changed
(the redline), not re-read the entire document.  A CEO doesn't review
50-page reports without redlines.

Zero external dependencies — pure Python dataclass.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class FeedbackDiff:
    """Semantic diff between two iterations of the feedback loop."""
    iteration: int
    new_observations: list[str] = field(default_factory=list)
    changed_assessments: list[str] = field(default_factory=list)
    removed_items: list[str] = field(default_factory=list)
    unchanged_count: int = 0
    delta_summary: str = ""  # generated by a short Sonnet call

    @property
    def is_material(self) -> bool:
        """Did the feedback introduce material changes?"""
        return len(self.new_observations) > 0 or len(self.changed_assessments) > 0

    def format_for_gate(self) -> str:
        """Format the diff for presentation at a pipeline gate."""
        lines = [f"Feedback iteración {self.iteration}:"]

        if self.new_observations:
            lines.append(f"  + {len(self.new_observations)} observaciones nuevas")
            for obs in self.new_observations[:5]:  # cap display
                lines.append(f"    - {obs}")

        if self.changed_assessments:
            lines.append(f"  ~ {len(self.changed_assessments)} assessments cambiaron")
            for chg in self.changed_assessments[:5]:
                lines.append(f"    - {chg}")

        if self.removed_items:
            lines.append(f"  - {len(self.removed_items)} items removidos")

        if self.unchanged_count > 0:
            lines.append(f"  = {self.unchanged_count} items sin cambios")

        if self.delta_summary:
            lines.append(f"\n  Resumen: {self.delta_summary}")

        return "\n".join(lines)

    def format_for_event(self) -> dict:
        """Serialize for EventBus persistence."""
        return {
            "iteration": self.iteration,
            "new_observations": self.new_observations,
            "changed_assessments": self.changed_assessments,
            "removed_items": self.removed_items,
            "unchanged_count": self.unchanged_count,
            "delta_summary": self.delta_summary,
            "is_material": self.is_material,
        }
